global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Spring Boot Actuator metrics
  - job_name: 'carrental-app'
    static_configs:
      - targets: ['app:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']