package com.example.carrental.enums;

public enum NotificationType {
    RESERVATION_CONFIRMATION,
    PAYMENT_CONFIRMATION,
    PICKUP_REMINDER,
    RETURN_REMINDER,
    PROMOTIONAL,
    MAINTENANCE_ALERT,
    WELCOME,
    LOYALTY_REWARD,
    REFUND_CONFIRMATION,
    DAILY_REPORT,
    WEEKLY_REPORT,
    MONTHLY_INVOICE
}